[package]
name = "probably-net"
version = "0.1.0"
authors = ["Adam Shirey <adam@shirey.ch>"]
edition = "2018"

[dependencies]
libc = "*"
probably = "0.3.1"

[lib]
name = "probably_net"
crate-type = ["cdylib"]
